apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: image-pipelinerun
spec:
  params:
  - name: CHAINS-GIT_COMMIT
    value: my-git-commit
  - name: CHAINS-GIT_URL
    value: https://my-git-url
  pipelineSpec:
    results:
    - description: ""
      name: IMAGE_URL
      value: $(tasks.buildimage.results.IMAGE_URL)
    - description: ""
      name: IMAGE_DIGEST
      value: $(tasks.buildimage.results.IMAGE_DIGEST)
    tasks:
    - name: buildimage
      taskSpec:
        results:
        - name: IMAGE_URL
          type: string
        - name: IMAGE_DIGEST
          type: string
        steps:
        - image: bash:latest
          name: create-dockerfile
          resources: {}
          script: |-
            #!/usr/bin/env bash
            echo 'gcr.io/foo/bar' | tee $(results.IMAGE_URL.path)
            echo 'sha256:05f95b26ed10668b7183c1e2da98610e91372fa9f510046d4ce5812addad86b5' | tee $(results.IMAGE_DIGEST.path)
          volumeMounts:
          - mountPath: /dockerfile
            name: dockerfile
        volumes:
        - emptyDir: {}
          name: dockerfile
          